<a href="https://colab.research.google.com/github/daigokawabe/Flask_First_WebApp/blob/master/1st_day_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Numpy and Matplotlib

![Imgur](https://i.imgur.com/8prlyQj.jpg)



### What you will learn today
* Install Numpy, Matplotlib and set up their environment
* Explain each library
* How to use basic Numpy
* How to use basic Matplotlib
* Practice



### IT words learning in lesson
- dimension : 次元
- vector : ベクトル
- multidimensional array : 多次元配列
- dot product : 内積
- scatter : 散布図

## 1.1. Numpy

There are many useful libraries in Python. Especially, NumPy, a library of Python, is essential to calculate numerical value and value in science and technology field.  
If we use NumPy to implement and calculate linear algebra that is often used in the filed of deep learning, we can do it quite efficiently.
We will learn how to use basic NumPy and think about an image to implement formula.

When you installed Anaconda, NumPy is installed at the same time.
    "If you do not use Anaconda, you can install it easily as follows.
```bash
pip install numpy
```

### 1.1.1 ndarray
There is data type called **list** to deal with arrays including multidimensional array in Python.  
We use this list to calculate matrix. However, we can not get the result of matrix calculation as calculating `A + B` and `A * B` unless we implement function by ourselves in matrix calculation.
We calculate as follows now.


In [0]:
A = [[1,0], [0,1]]
B = [[1,2], [3,4]]

print(A + B)

[[1, 0], [0, 1], [1, 2], [3, 4]]


The result is as follows.
```
[[1, 0], [0, 1], [1, 2], [3, 4]]
```
Returned list is just combined the values of A and B.

We use **ndarray** in Numpy now. 
ndarray is not flexible as arrays than Python of list but it specializes in matrix calculation.
Numpy is used in `C`, programming language that is faster than `Python`. When we use ndarray in matrix calculation, it is beneficial to have a fast.
We calculate addition of matrix now.


In [0]:
import numpy as np

A = np.array([[1,0], [0,1]])
B = np.array([[1,0], [0,1]])

print(A + B)

[[2 0]
 [0 2]]


First of all, first line, 

```python
import numpy as np
```

This imports numpy and it is used the alias in `np` because the function of numpy is often used in the code repeatedly.  

The result is as follows.
```
[[2 0]
[0 2]]
```
It is the correct result in matrix calculation.

Remember that ndarray is a class to deal with multidimensional array and it has the restriction as follows.

 * All types of element in array is same
 * Array length is fixed(Fixed length array)
 * The number of element is same in arrays of each dimension


### 1.1.2 The Attributes of ndarray

We learn about the attributes of ndarray now.
It is often used in the code.


| Attribute | Explanation |
| :--- | :---- |
| ndarray.flags | Memory layout information in array data (numpy.flagsobj) |
| ndarray.ndim | Number of dimenstion in arrays |
| ndarray.size | Number of element in arrays |
| ndarray.shape | Number of element in each dimention |
| ndarray.itemsize | Number of a byte in element |
| ndarray.strides | Needed number of byte to move next element in each dimension |
| ndarray.nbytes | Number of byte in all arrays |
| ndarray.dtype | Data type in element of array (numpy.dtype) |

We output this to the console in Jupyter now.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


First of all, we prepared `4 * 3 (height*width)` of matrix.

In [0]:
print(A.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


Keep going.

In [0]:
print(A.ndim) # ndim == This means N dimension!

2


Strictly speaking, this dimension shows the axis number.
In our opinion, the dimension of vector is the number of elements in the arrays,  
in other words, 
```
a = [1,2,3]
```
in this case, `a` is third dimension of vector
```
b = [1,2,3,4]
```
In this case, `b` is fourth dimension of vector.

However, ndarray specializes in multidimensional array. We will learn about the concept, **tensor**, tomorrow. ndim shows the axis number.
In `A` case,
```
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
 ```
 This has two axes, height and width, so this multidimensional array is second dimension.


In [0]:
print(A.size)

12


This is the result of `4 * 3`. In short, the number of elements.

In [0]:
print(A.shape)

(4, 3)


This shows `4 * 3` itself.

In [0]:
tate, yoko = A.shape
print("tate: {}".format(tate))
print("yoko: {}".format(yoko))

tate: 4
yoko: 3


When we wrote like this, we can set the size of height and width.

We learn about others.

In [0]:
print(A.itemsize)
print(A.strides)
print(A.nbytes)
print(A.dtype)

8
(24, 8)
96
int64


To be honest, these are rarely used except `dtype`.
dtype shows the element type. However, when we write as follows, we will get the different result.

In [0]:
B = np.array([1.0,2.0,3.0,4.0,5.0])
print(B.dtype)

float64


### 1.1.3 Vector and Matrix Calculation with Numpy

Remember that the calculation with numpy, ndarray to be often used in coding.


#### Addition | 和
```
a + b
```

In [0]:
a = np.array([1,2,3])
b = np.array([-3,-2,-1])

print(a + b)

[-2  0  2]


In [0]:
print(a + 3)

[4 5 6]


We calculate this in matrix now

In [0]:
A = np.array([[1,0], [0,1]])
B = np.array([[1,0], [0,1]])
print(A + B)

[[2 0]
 [0 2]]


#### Multiplication | 積
```
a * b
A * B
```

In [0]:
print(a * b)

[-3 -4 -3]


In [0]:
print(A * B)

[[1 0]
 [0 1]]


#### Dot Product | 内積
```
np.dot(a, b)
np.dot(A, B)
```

In [0]:

print(np.dot(a, b))

-10


In [0]:
print(np.dot(A, B))

[[1 0]
 [0 1]]


There is the one thing that we need to be careful when we calculate an dot product  in matrix.
It is `shape` in two matrix.

In [0]:
print(A.shape)
print(B.shape)

(2, 2)
(2, 2)


It does not occur problem in this case, A and B of matrix, due to square matrix with the same number of rows and columns.
    "It must correspond to the number of columns, multiplied number, and rows, multiplying number, in dot product.
    
We calculate it now.

In [0]:
import numpy as np

X = np.array([[1,2], [3,4], [5,6]])            # Matrix of 3 * 2 (rows * columns)
Y = np.array([[7,8], [9, 10], [11, 12]])   # Matrix of 3 * 2 (rows * columns)

print(np.dot(X, Y.T))

[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]]


In [0]:
print(np.dot(X, (Y.T)))

[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]]


### 1.1.4 Create an Array and Multidimensional Array 

It is several methods to initialize an array in Numpy.
For example, we can create vector and matrix that all element are 0 and update specific place values later. 
This is super useful in Machine Learning and great advantageous to create the program after we firstly decided `shape`.

The methods to initialize are `np.zeros(shape)` and `np.ones(shape)`. 

* `np.zeros(shape)` : The element of array or matrix is initialized 0
* `np.ones(shape)` : The element of array or matrix is initialized 1 

They pass tuple as `shape` in each argument.

In [0]:
L = np.zeros((2,3))
print(L)
print(L.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


Easy to understand. The case of vector is also same. 
In vector, it does not need tuple.

In [0]:
l = np.ones(4)
print(l)
print(l.shape)

[1. 1. 1. 1.]
(4,)


When we use `np.arange()`, we can create the array with a range of value. 

In [0]:
m = np.arange(4)
print(m)
print(m.__class__.__name__)

[0 1 2 3]
ndarray


It starts at 0 in the default and returns the array(ndarray) with length of the number passed by the argument.

With second argument, it returns the array (ndarray), first argument to the number subtracting 1 from second argument and increasing number one by one. 

In [0]:
n = np.arange(4, 10)
print(n)
print(n.__class__.__name__)

[4 5 6 7 8 9]
ndarray


Moreover, with third argument, we can specialize in X to increase by X. 
In this case, the number will increase within second argument. 

In [0]:
k = np.arange(4 ,10, 2)
print(k)
print(k.__class__.__name__)

[4 6 8]
ndarray


### 1.1.5 Slice

When we use slice in ndarray, we can get the elements as list.
We specify the index and get the elements now.

In [0]:
a = np.arange(10)
print(a)
print(a[0])
print(a[9])
print(a[-1])

[0 1 2 3 4 5 6 7 8 9]
0
9
9


When we get partial arrays,

In [0]:
print(a[1:5])

[1 2 3 4]


```
variable name [first index:last index+1]

# JP
変数名[最初のインデックス:最後のインデックス+1]
```


we get partial arrays
as above.

In [0]:
print(a[4:])
print(a[:4])

[4 5 6 7 8 9]
[0 1 2 3]


We can also get partial arrays by writing another index.

```
variable name[specified index:] => It returns the partial index no less than specified index.
variable name[:specified index] => It returns the partial index no more than specified index(including specified index).
```

Remember that we got the partial index.

There is more complicated way to get partial index.

In [0]:
print(a[1:8:3])

[1 4 7]


This specifies
```
variable name[first index:last index + 1:the interval from first to last]

# JP
変数名[最初のインデックス:最後のインデックス + 1:最初から最後までの間隔]
```
We apply this as follows.

The following is advanced version of this.

In [0]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


We can sort the arrays in opposite order easily.

We can also use these slice in matrix.
Prepare `ndarray` of matrix now.

In [0]:
A = np.arange(1, 6+1).reshape(2,3)
print(A)

[[1 2 3]
 [4 5 6]]


It shows a bit little interesting in this type. We use `np.reshpae()`, a function, after we used `np.arange()`.
This reshape is a function that changes the arrays to shape, the argument of reshape function. 

We use slice now.

In [0]:
print(A[:2])

[[1 2 3]
 [4 5 6]]


This is same as before because A is second dimension from the start.

In [0]:
print(A[:1, 0])
print(A[:2, 1])

[1]
[2 5]


In [0]:
print(A[:2, ::-1])

[[3 2 1]
 [6 5 4]]


We can also sort each row of array.

## 1.2. Matplotlib

## slide: false


```py3
import numpy as np
import matplotlib.pyplot as plt
```

It is imported necessary module as above and we explain this chapter under it. 

# Plot data points

```py3
x = [1,2,3,4]
y = [5,6,7,8]
plt.plot(x, y, 'o-', label="my data") # plot ... w lp title "my data"
plt.xlabel("X")         # set xlabel "X"
plt.ylabel("Y")         # set ylabel "Y"
plt.legend(loc='best')  # set key
plt.show()
```

![image](https://qiita-image-store.s3.amazonaws.com/0/28792/37f136e5-fb4e-8507-2b45-52f02a10f8e8.png)

Corresponding gnuplot command that is written in the comment.

he third argument in `plot()` shows the format of display data. 'o' shows round marker, '-' shows line type.

When we specified `loc='best'` as the argument in `plt.legend`, it chooses the place of graph legends. If we choose best as default, it will be useful.

## Multiple series of plots 

```py3
x = [1,2,3,4]
y1 = [5,6,7,8]
y2 = [4,2,8,6]

plt.plot(x, y1, 'o-', label='y1')  # plot ....
plt.plot(x, y2, 'o-', label='y2')  # replot ...
plt.legend(loc='best')             # set key
plt.show()
```

![image](https://qiita-image-store.s3.amazonaws.com/0/28792/9900ff1c-a42f-29ef-1af3-cffee96f0234.png)

The plots are added more and more while we call `plot` in several times. When we call `show()`, they are drawn for the first time. 

# Plot the functions 

We need to add the data points by ourselves because it can not plot giving the functions.
Idiom that uses `np.arange`. 

```py3
x = np.arange(-3.0, 3.0, 0.01)
y = np.sin(x) * np.exp( -x)
plt.plot(x, y, '-')
plt.show()
```

![image](https://qiita-image-store.s3.amazonaws.com/0/28792/847228c1-9f43-b49d-2457-6f3e441929a1.png)

# Use log scale

```py3
x = np.arange( -3.0, 3.0, 0.01 )
y = np.exp(-x) * np.cos(x)*np.cos(x)
plt.plot(x, y, '-')
plt.yscale('log')
plt.show()
```

![image](https://qiita-image-store.s3.amazonaws.com/0/28792/17e9ae0b-ad31-d22e-bde2-ae9e158b02a4.png)

When we want to use linear scale, for example, we write `plt.xscale('linear')`.

# Loading the data from the file

For example, we have a file "test.dat" as follows.

```txt:test.dat
1 2 4
3 4 9
5 6 2
7 8 4
```

In order to plot this, 

```testdat.py
# "cols", "names", "delimiter" arguments are mandatory.
plt.plotfile('test.dat', cols=(0,1), names=('x','y'), delimiter=' ', marker='o', linestyle='--')
plt.show()
```

we write as above. If we omit `delimiter`, `names` and `cols`, it will not be displayed.
Especially, when we omit `names`, the first row is interpreted as the header row and the first row of data will disappear. 

![image](https://qiita-image-store.s3.amazonaws.com/0/28792/17ac45cf-3fb1-0036-c3a0-c503ce6c70b5.png)

In another way, we use numpy and load the data.

```py3
np.loadtxt("test.dat", comments='#', delimiter=' ')
plt.plot( dat[:,0]/1000, dat[:,1], 'o-' )
```

## Plot of the result in multiple columns

```py3
names = ('x','y1','y2')
plt.plotfile('test.dat', cols=(0,1), names=names, delimiter=' ', label="y1")
plt.plotfile('test.dat', cols=(0,2), names=names, delimiter=' ', label="y2", newfig=False)
plt.legend(loc='best')
plt.show()
```

![image](https://qiita-image-store.s3.amazonaws.com/0/28792/e07e6481-3a7d-5e80-60c2-912657d4fad0.png)

In another way, we use `numpy#loadtxt`.
  
    
We use scatter to draw scatter plots. 
We will give you some examples the following.

## Simple scatter plots
See the example about most simple scatter plots in the below figure.

```py
import numpy as np
import matplotlib.pyplot as plt

# generate data
x = np.random.rand(100)
y = np.random.rand(100)

fig = plt.figure()

ax = fig.add_subplot(1,1,1)

ax.scatter(x,y)

ax.set_title('first scatter plot')
ax.set_xlabel('x')
ax.set_ylabel('y')

fig.show()
```
![scatter01.png](https://qiita-image-store.s3.amazonaws.com/0/100523/53d0dd61-99f4-c8eb-3659-aa8602f0a85a.png)

## Change the color for each data
We can change the colors specifying as c='red' to the parameter.

```py
import numpy as np
import matplotlib.pyplot as plt

# generate data
x1 = np.random.rand(100)*0.5
y1 = np.random.rand(100)

x2 = np.random.rand(100)*0.5 + 0.5
y2 = np.random.rand(100)

fig = plt.figure()

ax = fig.add_subplot(1,1,1)

ax.scatter(x1,y1, c='red')
ax.scatter(x2,y2, c='blue')

ax.set_title('second scatter plot')
ax.set_xlabel('x')
ax.set_ylabel('y')

fig.show()
```
![scatter02.png](https://qiita-image-store.s3.amazonaws.com/0/100523/7af37198-eaad-b08b-c604-305775260c41.png)

If we specify RGB, the result will be same. We specify the value between 0.0 and 1.0 at this time. 

```py
ax.scatter(x1,y1, c=(1.0,0,0))
ax.scatter(x2,y2, c=(0, 0, 1.0))
```

## Add graph legends and grid lines
We use legend to add the graph legends. We can adjust the position displayed with argument. 
When we want to add grid line, we use grid(True). 

|position|
|:----:|
|upper right|
|upper left |
|lower left |
|lower right|
|right      |
|center left|
|center right|
|lower center|
|upper center|
|center      |

```py
import numpy as np
import matplotlib.pyplot as plt

# generate data
x1 = np.random.rand(100)*0.5
y1 = np.random.rand(100)*0.5

x2 = np.random.rand(100)*0.5 + 0.5
y2 = np.random.rand(100)*0.5

x3 = np.random.rand(100)*0.5
y3 = np.random.rand(100)*0.5 + 0.5

x4 = np.random.rand(100)*0.5 + 0.5
y4 = np.random.rand(100)*0.5 + 0.5

fig = plt.figure()

ax = fig.add_subplot(1,1,1)

ax.scatter(x1,y1, c='red', label='group1')
ax.scatter(x2,y2, c='blue', label='group2')
ax.scatter(x3,y3, c='green', label='group3')
ax.scatter(x4,y4, c='yellow', label='group4')

ax.set_title('third scatter plot')
ax.set_xlabel('x')
ax.set_ylabel('y')

ax.grid(True)

ax.legend(loc='upper left')
fig.show()
```
![scatter03.png](https://qiita-image-store.s3.amazonaws.com/0/100523/46ab6f30-773e-cec3-daed-2a8d59ca5d1e.png)

## Change the markers 
We specify the markers as marker='o'. \n",
    "We will give you the examples about representative four markers. There are more. [Here]For details refer to(http://matplotlib.org/api/markers_api.html#module-matplotlib.markers).

```py
import numpy as np
import matplotlib.pyplot as plt

# generate data
x1 = np.random.rand(100)*0.5
y1 = np.random.rand(100)*0.5

x2 = np.random.rand(100)*0.5 + 0.5
y2 = np.random.rand(100)*0.5

x3 = np.random.rand(100)*0.5
y3 = np.random.rand(100)*0.5 + 0.5

x4 = np.random.rand(100)*0.5 + 0.5
y4 = np.random.rand(100)*0.5 + 0.5

fig = plt.figure()

ax = fig.add_subplot(1,1,1)

ax.scatter(x1,y1, c='red', marker='.', label='group1')
ax.scatter(x2,y2, c='blue',marker='o', label='group2')
ax.scatter(x3,y3, c='green',marker='^', label='group3')
ax.scatter(x4,y4, c='yellow',marker='s', label='group4')

ax.set_title('fourth scatter plot')
ax.set_xlabel('x')
ax.set_ylabel('y')

ax.grid(True)

ax.legend(loc='upper left')
fig.show()
```
![scatter04.png](https://qiita-image-store.s3.amazonaws.com/0/100523/1014c993-9362-c8b1-dee5-2927d5bcc8fc.png)

## Change the size of markers
We set the size of markers to the parameter as s=20. The default is 20.

```py
import numpy as np
import matplotlib.pyplot as plt

# generate data
x1 = np.random.rand(100)*0.5
y1 = np.random.rand(100)*0.5

x2 = np.random.rand(100)*0.5 + 0.5
y2 = np.random.rand(100)*0.5

x3 = np.random.rand(100)*0.5
y3 = np.random.rand(100)*0.5 + 0.5

x4 = np.random.rand(100)*0.5 + 0.5
y4 = np.random.rand(100)*0.5 + 0.5

fig = plt.figure()

ax = fig.add_subplot(1,1,1)

ax.scatter(x1,y1, c='red', s=20, marker='o', label='group1')
ax.scatter(x2,y2, c='blue',s=40, marker='o', label='group2')
ax.scatter(x3,y3, c='green',s=80, marker='o', label='group3')
ax.scatter(x4,y4, c='yellow',s=120, marker='o', label='group4')

ax.set_title('fifth scatter plot')
ax.set_xlabel('x')
ax.set_ylabel('y')

ax.grid(True)

ax.legend(loc='upper left')
fig.show()
```
![scatter05.png](https://qiita-image-store.s3.amazonaws.com/0/100523/0eddee23-fb54-f05c-eef6-b70a7dbd9b6e.png)



###Just want to display

If we just want to display, we can use Image.show() method.
Each standard viewer will open.

```py
#coding:utf-8
from PIL import Image

#Load the images
im = Image.open("./achan.jpg")

#Display
im.show()
```

![py2](http://www.bluecode.jp/qiita/python02/001.png)


###Standard Python program

If we want to display the images in standard? Python program, we can use Matplotlib as same as drawing the graphs. 
It is probably useful and convenient because we can add the caption etc.

```py
#coding:utf-8
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np

#Load the images
im = Image.open("./achan.jpg")

#Conver the images to array
im_list = np.asarray(im)

# Paste
plt.imshow(im_list)

# Display
plt.show()
```

![py2](http://www.bluecode.jp/qiita/python02/002.png)

Apparently the pixels were mapped on the coordinates. 

###Jupyter

When we want to display the images in notebook of Jupyter(IPython), we add %matplotlib inline at the beginnig of the program. 
Then, it is displayed inline(if not so, another window will open).

>We can add inline option when we launched notebook. We recommend that you will do this if you do not want to change the code.

```py
#coding:utf-8
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np

#Declare to display inline with Jupyter
%matplotlib inline #Add

#Load the images
im = Image.open("./achan.jpg")

#Conver the images to array
im_list = np.asarray(im)
#Paste
plt.imshow(im_list)
#Display
plt.show()
```

![py2](http://www.bluecode.jp/qiita/python02/003.png)



In [0]:
from google.colab import drive
drive.mount('/content/drive')

## Activity

1 Create csv data by yourself then load it in your python file  
2 Set the x and y axes and explain what they mean




### FYI
There’s one package you need to learn for data science. It’s called pandas.

Pandas is like Excel in Python: it uses tables (namely DataFrame) and operates transformations on the data. But it can do a lot more.

- Tutorial  
https://data36.com/pandas-tutorial-1-basics-reading-data-files-dataframes-data-selection/

- You can also do it  
https://github.com/simongeek/PandasDA



